#!/bin/bash

# Small script that manually adds some openflow flows to the testing topology
# generated by "topo-test.py".


# Delete previous flows in case there are any.
sudo ovs-ofctl del-flows s1

# Make sure ARP messages reach their destination (although not very efficiently).
sudo ovs-ofctl add-flow s1 arp,actions=flood

# Allow the hosts to ping themselves.
sudo ovs-ofctl add-flow s1 ip,nw_dst=10.0.0.1,actions=output:2
sudo ovs-ofctl add-flow s1 ip,nw_dst=10.0.0.2,actions=output:3

# Attempt at trying to reach the external interface.
# EDIT: After some testing, it actually works, hooray!
sudo ovs-ofctl add-flow s1 ip,nw_dst=10.0.0.100,actions=output:1

# Show the flows.
sudo ovs-ofctl dump-flows s1
